### ISSUE TITLE
gcp connector and rhel version

### ISSUE THREAD

**Issue by trevorjth** [NetAppDocs/cloud-manager-setup-admin#105]
Page: [Default configuration for the Connector](https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-connector-default-config.html)

This may already be scheduled to update, but just an fyi, in gcp, SaaS/gcloud deployment is deploying with rhel 8.6 at this point:
Google Cloud details
If you deployed the Connector from BlueXP or from the cloud provider’s marketplace, note the following:

The VM instance is n2-standard-4.

The operating system for the image is CentOS 7.9.

The operating system does not include a GUI. You must use a terminal to access the system.

The default system disk is a 100 GiB SSD persistent disk.

**Comment by netapp-bcammett** [comment]
I updated the OS to RHEL 8.6. Thanks again!
