### ISSUE TITLE
Link broken - https://review.docs.netapp.com/us-en/cloud-manager-setup-admin_nov-2022/task-manage-subscriptions.html

### ISSUE THREAD

**Issue by kholger** [NetAppDocs/cloud-manager-setup-admin#108]
Page: [What’s new](https://docs.netapp.com/us-en/cloud-manager-setup-admin/whats-new.html)

Your PAYGO subscriptions and annual contracts for BlueXP are now available to view and manage from the Digital Wallet.

[Learn how to manage your subscriptions](https://review.docs.netapp.com/us-en/cloud-manager-setup-admin_nov-2022/task-manage-subscriptions.html)

**Comment by netapp-bcammett** [comment]
Thank you, @kholger. I fixed the link.
