### ISSUE TITLE
More detailed instructions on Federated SSO?

### ISSUE THREAD

**Issue by elfcounsel** [NetAppDocs/cloud-manager-setup-admin#11]
Page: [Logging in to Cloud Manager](https://docs.netapp.com/us-en/occm/task_logging_in.html)

Is it possible to get a detailed how-to on how to configure federated access, or links to the Azure AD, ADFS, etc specific docs which explain how to make this work? 

Is it also possible to get Cloud Manager qualifed and added to this list https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/tutorial-list?

Thanks!

**Comment by ntap-bmegan** [comment]
This issue will be closed on tues 30 aug 2022 due to lack of activity within the last 30 days. @elfcounsel - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

**Comment by netapp-bcammett** [comment]
No worries--we're going to keep this issue open. I'm waiting for enhancements from our Cloud Central team before I can help update the instructions for federated access.

**Comment by ntap-bmegan** [comment]
Thanks, @netapp-bcammett!

**Comment by ntap-bmegan** [comment]
@netapp-chandaj - This issue is marked as waiting on info, so it shouldn't be closed. That said, @netapp-bcammett, any update? It's been a while.

**Comment by netapp-bcammett** [comment]
The following page was added to the docs: 
https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-federation.html

This page provides an overview how identity federation works and an overview of the setup process.

At some point, changes will be made to the federation setup page on cloud.netapp.com to improve the individual steps that are needed to enable identity federation with BlueXP:
https://services.cloud.netapp.com/federation-setup

Changes to that page will be completed by the product team are outside of my control.

Thanks,
Ben
