### ISSUE TITLE
Remove outdated endpoint URL

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/cloud-manager-setup-admin#112]
Page: [Install the Connector on an existing Linux host that has internet access](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-installing-linux.html)

Hi- On this page under "Outbound Internet Access" the following URL is no longer needed and can be removed from documentation:

`https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm`

Liraz just confirmed this .

**Comment by netapp-bcammett** [comment]
@mimitche, thank you for letting me know. I'll work on the doc update and let you know when it's done.

**Comment by netapp-bcammett** [comment]
Mike,

I fixed this in the docs last week.

Thanks again,
Ben
