### ISSUE TITLE
wrong information for Apply security updates

### ISSUE THREAD

**Issue by cuiguoxing** [NetAppDocs/cloud-manager-setup-admin#114]
Page: [Managing existing Connectors](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-managing-connectors.html)

sudo -s
service service-manager stop
yum -y update –-security
service service-manager start

For the GCP, the service name is 'netapp-service-manager'

output：

[lod_pool_user_96@gcpconnector ~]$ service service-manager status
Redirecting to /bin/systemctl status service-manager.service
Unit service-manager.service could not be found.
[lod_pool_user_96@gcpconnector ~]$ service netapp-service-manager status
Redirecting to /bin/systemctl status netapp-service-manager.service
● netapp-service-manager.service - Netapp Service Manager
   Loaded: loaded (/usr/lib/systemd/system/netapp-service-manager.service; enabled; vendor preset: disabled)

Pls add GCP commands.

Thanks,

Allen

**Comment by netapp-bcammett** [comment]
@cuiguoxing, thank you for submitting this feedback. I will confirm with the product team and update the docs accordingly.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
Hi there,

The docs now include the correct name for the service:

> sudo -s
> service netapp-service-manager stop
> yum -y update –-security
> service netapp-service-manager start

Thanks again,
Ben
