### ISSUE TITLE
update requirements for manual install at 3.9.23 and above

### ISSUE THREAD

**Issue by trevorjth** [NetAppDocs/cloud-manager-setup-admin#115]
Page: [Install the Connector on an existing Linux host that has internet access](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-installing-linux.html)

3.9.23 installer on NSS now supports RHEL 8.x as well.
3.9.23 does not install docker anymore, but requires it to be installed and enabled.
Manual install flags have changed from:  ./OnCommandCloudManager-V3.9.19.sh [silent] [proxy=ipaddress] [proxyport=port] [proxyuser=user_name] [proxypwd=password]

To: /OnCommandCloudManager-V3.23.sh --proxy http://occm:password@10.0.0.30:9090/ --cacert /root/rootca.pem

Unsure if there are other updates required with this new release.

**Comment by netapp-bcammett** [comment]
Hi Trevor,

Thank you for reaching out. I've been chatting with the development team over the last 24 hours to learn more about the installer changes. I should hopefully have the docs updated soon once I get the full details.

Thanks again,
Ben

**Comment by trevorjth** [comment]
Appreciate that Ben, thank you!

Trevor

**Comment by netapp-bcammett** [comment]
Trevor,

I updated the docs to include RHEL 8.6 and I also updated the installation command. I'm continuing discussion with the development team to identify any additional changes.

Thanks,
Ben
