### ISSUE TITLE
Connector Advanced Outbound Firewall Rules

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/cloud-manager-setup-admin#12]
Page: [Networking requirements for Cloud Volumes ONTAP in GCP](https://docs.netapp.com/us-en/occm/reference_networking_gcp.html)

On this page, under "Advanced Outbound Rules" for the connector, it lists various outbound ports going to Active Directory.  Are these outdated?  I did not think Cloud Manager used AD directly for authentication anymore, with all user auth happening via Cloud Central.

**Comment by netapp-bcammett** [comment]
I received confirmation that the Active Directory ports are no longer used by the Connector. I removed them from the docs. Thank you for your patience.

Regards,
ben
