### ISSUE TITLE
stray < character

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/cloud-manager-setup-admin#123]
Page: [Create a Connector in Google Cloud from BlueXP](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-gcp.html)

````
  --service-account=<<service-account>
````

I think that `<<` should be just one `<` character.

https://github.com/NetAppDocs/cloud-manager-setup-admin/blob/main/task-creating-connectors-gcp.adoc?plain=1#L476

**Comment by netapp-bcammett** [comment]
Thanks. I'll fix this in the next doc update.

**Comment by netapp-bcammett** [comment]
This issue has been fixed. Thanks again!
