### ISSUE TITLE
Missing permission in policy 1 permission list

### ISSUE THREAD

**Issue by trevorjth** [NetAppDocs/cloud-manager-setup-admin#126]
Page: [AWS permissions for the Connector](https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-permissions-aws.html)

![image](https://user-images.githubusercontent.com/109701535/208136326-8a7b8612-9e22-49da-ba65-1ed72a747b31.png)

These two permissions are missing from the policy1 list of permissions that customers are using on this page:

Create and manage aggregates that support the Amazon EBS Elastic Volumes feature  
ec2:DescribeVolumesModifications
ec2:ModifyVolume

**Comment by netapp-bcammett** [comment]
@trevorjth,

Thank you for letting me know. I'm working on getting the first policy updated.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
Policy 1 was updated for standard regions.
https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-permissions-aws.html#iam-policies

Thanks again,
Ben
