### ISSUE TITLE
Two URL's for outbound connection from connector missing

### ISSUE THREAD

**Issue by kholger** [NetAppDocs/cloud-manager-setup-admin#128]
Page: [Getting started checklist](https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html)

When deploying BlueXP conncector we realized that two additional outbound URL's were required to start working properly with the connector:

1. https://management.azure.com
2. https://cognito-identity.us-east-1.amazonaws.com (for enabling CBS)

Thx
Holger

**Comment by netapp-bcammett** [comment]
@kholger,

Are you saying that these outbound URLs are contacted from the user's web browser when using the BlueXP console to create a Connector?

Or are you saying the that Connector itself contacts these URLs?

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
@kholger, can you please take a look at the questions in my previous comment?

Thanks!

**Comment by kholger** [comment]
Apologize for my delayed answer, still working against my backlog.
The URLs are called from the connector that actually makes sense as the connector has to reach the Azure API endpoint https://management.azure.com/

The URL https://cognito-identity.us-east-1.amazonaws.com/ was disbaled by customer's firewall and we saw requests coming from the connector when we tried to enable CBS on it.
![image](https://user-images.githubusercontent.com/92466880/211880725-e3ba39a5-0d5c-421c-9436-beda0f91fc76.png)

**Comment by netapp-bcammett** [comment]
Thanks, I just wanted to confirm because both of the endpoints that you mentioned are listed as required from the BlueXP user interface via the user's web browser: https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html

But if those endpoints are also being contacted by the Connector instance, then I'll need to confirm the list of endpoints with the product team. I'll reach out to them.

Thanks,
Ben

**Comment by kholger** [comment]
I happened in an environment where connector was only able to access whitelisted URLs.
Both URLs had been blocked initially and connector was not fully funcational with that. It worked after whitelisting both URLs (based on the requests we saw in the FW logs)

Thanks for checking with engineering.

**Comment by netapp-bcammett** [comment]
@kholger,

The docs have been updated to include the specific cloud provider endpoints that the Connector contacts. Note that engineering stated that the Connector does _not_ contact this endpoint: 

https://cognito-identity.us-east-1.amazonaws.com

If that is not right from your perspective, you would need to reach out to the cloud solutions architects.

Thanks,
Ben
