### ISSUE TITLE
3128 inbound connector port

### ISSUE THREAD

**Issue by kholger** [NetAppDocs/cloud-manager-setup-admin#129]
Page: [Getting started checklist](https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html)

There’s no incoming traffic to the Connector, unless you initiate it.

HTTP (80) and HTTPS (443) provide access to the local UI, which you’ll use in rare circumstances. SSH (22) is only needed if you need to connect to the host for troubleshooting.

It hink it would be helpful also to refer to the option to use the conenctor as a proxy for sending ASUP. For this inbound 3128 would be required as described here: https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-launching-azure-mktp.html?q=auto (page bottom)

Thx
Holger

**Comment by netapp-bcammett** [comment]
@kholger,

I will add that. Thanks for pointing this out.

Regards,
Ben

**Comment by netapp-bcammett** [comment]
@kholger,

I made the change that you suggested:

> HTTP (80) and HTTPS (443) provide access to the local UI, which you’ll use in rare circumstances. SSH (22) is only needed if you need to connect to the host for troubleshooting. Meanwhile, inbound connections over port 3128 are required if you deploy Cloud Volumes ONTAP systems in a subnet where an outbound internet connection isn’t available.

Thanks again for your feedback.

Regards,
Ben
