### ISSUE TITLE
Where can I find the steps to create a connector in Azure?

### ISSUE THREAD

**Issue by yasuharu-k** [NetAppDocs/cloud-manager-setup-admin#13]
Page: [Set up and administer Cloud Manager](https://docs.netapp.com/us-en/cloud-manager-setup-admin/index.html)

Hi Team,

Our partner would like to know the steps to create a Connector in Azure.
As I recall, the procedure was posted in the document until April 4, 2022.
I would like to guide my partner to a website with instructions on how to do this, where can I find it?

And our partner wants to change the IP address of Connector and CVO. They want to use a specified IP address, not an automatically assigned one.
Please let me know where I can find instructions on how to change these IP addresses.
If it is not possible to change the IP address, we would appreciate it if you could clearly state this in the documentation as a "limitation".

Thanks & Best Regards,
Yasuharu

**Comment by netapp-bcammett** [comment]
Hi Yasuharu,

You were in the right place. The instructions can be found here:
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-azure.html

I will need to check on the question about changing the IP addresses. I'll let you know what I hear.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
Hi Yasuharu,

You can find instructions for changing the Connector's IP address here:
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-managing-connectors.html#change-the-ip-address-for-a-connector

Changing the IP address for Cloud Volumes ONTAP isn't supported. That's covered by the first limitation on the following page:
https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limitations.html

Thanks again for reaching out with this feedback.

Regards,
Ben
