### ISSUE TITLE
Improve step 12 explanation

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/cloud-manager-setup-admin#137]
Page: [Managing Google Cloud credentials and subscriptions for BlueXP](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-adding-gcp-accounts.html)

Currently, we say that "The GCP subscription will be linked to all NetApp accounts that your user login is associated with."
This is current behavior and correct so my proposal here is to add additional information to improve it.

With current behavior all accounts associated with the user will get permissions to charge through the new added subscription and that behavior, in some cases, could be problematic as charges can happen cross accounts.

Could you consider to add something like:
In case you need to limit the access to the new subscription, refer to [Managing subscriptions](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-managing-netapp-accounts.html#managing-subscriptions) to learn how to manage your subscriptions associations.

Thank you,
Gabriel

**Comment by netapp-bcammett** [comment]
Gabriel,

This is really good feedback. Thank you for submitting it. I went ahead and updated step 12 to include this info.

Regards,
Ben
