### ISSUE TITLE
Susbcription management changes

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/cloud-manager-setup-admin#138]
Page: [Managing your NetApp account](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-managing-netapp-accounts.html)

Current GUI has moved the Subscription management entry point from:
Account drop-down and click Manage Account

to the Digital Wallet -> Subscriptions
![image](https://user-images.githubusercontent.com/34706481/213176236-83adb4e1-467a-41d7-b967-0cbccd1e34b9.png)

Consider to update the section.

Regards,
Gabriel

**Comment by netapp-bcammett** [comment]
Gabriel,

Thank you for submitting this feedback. That section should have been removed as we added a new page for managing subscriptions in the Digital Wallet here:
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-manage-subscriptions.html

I went ahead and removed that section from the "Managing your NetApp account" page.

Thanks again,
Ben
