### ISSUE TITLE
Confusion about support without the SaaS interface

### ISSUE THREAD

**Issue by felix-melligan** [NetAppDocs/cloud-manager-setup-admin#14]
Page: [Known limitations](https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-limitations.html)

Could be worth mentioning how CBS, CDS and CI are available without the SaaS interface (pretty sure through dark site connector or Cloud Insights but not sure). Thanks!

**Comment by felix-melligan** [comment]
Hey Ben, that's correct, sorry the Monitoring service

**Comment by ntap-bmegan** [comment]
This issue will be closed on tues 30 aug 2022 due to lack of activity within the last 30 days. @felix-melligan - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

**Comment by netapp-bcammett** [comment]
No worries--we're going to keep this issue open. I'm waiting for additional details from product management before moving forward.

**Comment by ntap-bmegan** [comment]
Thanks, @netapp-bcammett!

**Comment by kholger** [comment]
Hi, just wonder if you got any update on this? This info would be very interesting for many customers. Thx

**Comment by netapp-bcammett** [comment]
@kholger,

An update is in the works. I'll send you a internal draft when it's ready so that I can get your feedback.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
The documentation was updated to explain the three BlueXP deployment modes:
https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-modes.html

Both restricted and private don't use the SaaS web-based interface.
