### ISSUE TITLE
HTTPS proxy supported or not?

### ISSUE THREAD

**Issue by kholger** [NetAppDocs/cloud-manager-setup-admin#140]
Page: [Install the Connector on an existing Linux host that has internet access](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-installing-linux.html)

On https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-configuring-proxy.html it is mentioned that BlueXP doesn't support HTTPS proxy.

It could be confusing that https is mentioned here as an option for the proxy parameters.
It would be good to clarify that only http:// proxy URLs are supported.

Thx

**Comment by kholger** [comment]
In addition, it would be helpful to mention, that system variables for $http_proxy and https_proxy shoud not be set.

**Comment by gandalftg** [comment]
having http_proxy or https_proxy in the user environment before running the installer will break the network connectivity check and will fail the installation
make sure to:
unset http_proxy
unset https_proxy

**Comment by netapp-bcammett** [comment]
Thanks to you both. I'm in active discussions with the product team about this issue. I'll be updating the docs as soon as I get clarification.

**Comment by netapp-bcammett** [comment]
I'm waiting to hear more from the product team, but for now I removed the statement about HTTPS proxy servers not being supported. I clarified that HTTP proxy servers are supported when configuring the Connector from the user interface.

I'll add the details about this next:

unset http_proxy
unset https_proxy

**Comment by netapp-bcammett** [comment]
I updated the docs to clarify that both HTTP and HTTPS proxies are supported. I also updated the Connector installation page to include the steps for unsetting http_proxy and https_proxy.

https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-installing-linux.html#install-the-connector

Thanks again to both of you for your help.

Regards,
Ben

**Comment by gandalfwfh** [comment]
Hi Ben,

I think there was a misunderstanding regarding the use of https in the proxy address.

https in the proxy address for example https://ip_address:port is NOT supported, A proxy address always starts with http

Regarding the "A CA-signed certificate, if the proxy server uses HTTPS" is not related to the proxy address.  When setting http proxy it's possible to force a use of certificate or no certificate, it's not related to the proxy address and it has to do with how the proxy was configured by he customer (use certificate or not), but it's still http.
