### ISSUE TITLE
Please add CBS to the list of unsupported features under Disable SaaS

### ISSUE THREAD

**Issue by wjthompson-ntap** [NetAppDocs/cloud-manager-setup-admin#141]
Page: [Managing your NetApp account](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-managing-netapp-accounts.html)

Please add Cloud Backup Service under the list of services not available from BlueXP with SaaS disabled.  Feel free to verify with Aviram.

**Comment by netapp-bcammett** [comment]
Thanks for submitting the issue. I will clarify with product management.

**Comment by netapp-bcammett** [comment]
@wjthompson-ntap,

I updated the docs as follows:

> The following services aren’t available from BlueXP if you disable the SaaS platform:
> 
> - Cloud Backup
> Cloud Backup is supported in Government regions when the SaaS platform is disabled, but not in commercial regions when the SaaS platform is disabled
> - Cloud Data Sense
> ...

Thanks again,
Ben
