### ISSUE TITLE
Update AWS to Azure - CVO Section

### ISSUE THREAD

**Issue by fritntap** [NetAppDocs/cloud-manager-setup-admin#145]
Page: [Azure permissions for the Connector](https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-permissions-azure.html)

Under the Cloud Volumes ONTAP section, it states:

"The Connector makes the following API requests to deploy and manage Cloud Volumes ONTAP in **AWS**."

However, this page is "Azure permissions for the Connector"

Therefore, the line should read: ""The Connector makes the following API requests to deploy and manage Cloud Volumes ONTAP in **Azure**."

**Comment by netapp-bcammett** [comment]
@fritntap,

Good catch! I'll make that update soon and reply back here when it's done.

Thank you for helping us make the docs better.

Regards,
Ben

**Comment by netapp-bcammett** [comment]
I fixed the typo. Thanks again!

**Comment by fritntap** [comment]
Awesome! Thanks for the quick update Ben, I appreciate it.
--
Nick
