### ISSUE TITLE
Update Associate an AWS subscription Video

### ISSUE THREAD

**Issue by mgraws** [NetAppDocs/cloud-manager-setup-admin#148]
Page: [Manage AWS credentials and subscriptions for BlueXP](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-adding-aws-accounts.html)

Hello,  Is it possible to update the video with the new BlueXP listing and BlueXP GUI?  Will be helpful to send out for those that forget to associate the subscription.

Matt

**Comment by netapp-bcammett** [comment]
Hi Matt,

This is in the works right now. I should have an update in a few days.

Thanks,
Ben

**Comment by mgraws** [comment]
Ben,

Great news!  Looking forward to it.

Matthew Robins
Cloud Solution Architect – AWS Alliance

NetApp
914.318.2629 Mobile Phone
***@***.******@***.***>

**Comment by netapp-bcammett** [comment]
Matt,

The AWS video and steps have been updated (I updated the Azure and Google Cloud pages as well).

Thanks again for submitting your feedback and helping us make the docs better.

Regards,
Ben
