### ISSUE TITLE
Advanced outbound rules for BlueXP connector security group

### ISSUE THREAD

**Issue by michaelrstewart1** [NetAppDocs/cloud-manager-setup-admin#154]
Page: [Security group rules in AWS](https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-ports-aws.html)

The advanced outbound rules section is for customers who want to explicitly define the outbound rules for the connector's security groups when they don't want to leave it completely open. When deploying Cloud Data Sense via BlueXP, the BlueXP connector probes the newly deployed Data Sense EC2 instance over port 8080. If the BlueXP connector does not have outbound access to the new EC2 instance over 8080 then the probe will time out and the Data Sense EC2 connector will be deconstructed.

Since outbound 8080 is required in this scenario we should have it included in the "Advanced outbound rules" table.

Service         Protocol          Port           Destination            Purpose
API calls        TCP                 8080         Data Sense             Probe to Data Sense instance during deployment

Something like this.

**Comment by netapp-bcammett** [comment]
@michaelrstewart1,

Thank you, this is great feedback. I assume this outbound port is required in Azure and Google Cloud as well?

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
I updated the docs with port outbound port 8080. Thanks again for reaching out with your feedback.

Regards,
Ben
