### ISSUE TITLE
Update to Permissions for the service account associated with the Connector instance.

### ISSUE THREAD

**Issue by trevorjth** [NetAppDocs/cloud-manager-setup-admin#155]
Page: [Create a Connector in Google Cloud from BlueXP](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-gcp.html)

Permissions for the service account associated with the Connector instance.

It appears that since the update to fix the multi SVM API was introduced, our connector now needs compute.instances.updatenNetworkInterface permission on the service account associated with a connector

![image](https://user-images.githubusercontent.com/109701535/219501793-bff93aea-3dea-4f4a-948f-d7bb8359cbff.png)

**Comment by netapp-bcammett** [comment]
@trevorjth,

Thank you for letting me know. I updated the policy with this permission.

Thanks again,
Ben

**Comment by trevorjth** [comment]
No problem, thanks Ben!
