### ISSUE TITLE
Update to endpoint requirements with aws

### ISSUE THREAD

**Issue by trevorjth** [NetAppDocs/cloud-manager-setup-admin#157]
Page: [Create a Connector in AWS from BlueXP](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-aws.html)
![image](https://user-images.githubusercontent.com/109701535/220469758-3939375d-915c-43f0-9211-bb93f7538371.png)

For AWS, our first endpoint in the list doesn't actually exist in DNS: https://<region>.amazonaws.com

It may be that we meant to put "https://*.<region>.amazonaws.com" or, we may want to put the actual service endpoints we require that are outlined here:
https://docs.aws.amazon.com/general/latest/gr/rande.html

**Comment by trevorjth** [comment]
looks like github is stripping some of my text, let me know if there are any questions, there is no service endpoint for us-east-1.amazonaws.com.  The service endpoints have subdomains below, for example "dynamodb.us-west-2.amazonaws.com"

**Comment by netapp-bcammett** [comment]
Thanks for submitting this feedback. I've reached out to our development lead to confirm the right syntax for the AWS endpoints that we contact.

**Comment by netapp-bcammett** [comment]
The AWS endpoints were updated to list the services that we contact.

![image](https://user-images.githubusercontent.com/18287750/223557501-34a244cf-bb47-4372-946e-937425f4eb41.png)

Thanks again for your feedback.

Regards,
Ben
