### ISSUE TITLE
AWS "I'm creating a Connector from Cloud Manager" policy is missing permissions

### ISSUE THREAD

**Issue by felix-melligan** [NetAppDocs/cloud-manager-setup-admin#16]
Page: [Create a Connector in AWS from Cloud Manager](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-aws.html)

Policy for the "I'm creating a Connector from Cloud Manager" policy is missing the permissions for iam:ListRoles and iam:ListAlias on page: https://s3.amazonaws.com/occm-sample-policies/Policy_for_Setup_As_Service.json

**Comment by netapp-bcammett** [comment]
Thanks, Felix. I forwarded this request to the team that manages the policy.
