### ISSUE TITLE
Wrong Service Name - Apply security updates

### ISSUE THREAD

**Issue by saschape** [NetAppDocs/cloud-manager-setup-admin#163]
Page: [Managing existing Connectors](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-managing-connectors.html)

sudo -s
service netapp-service-manager stop
yum -y update –-security
service netapp-service-manager start

Please check service stop / start, seems to be the wrong service name.
Correct should be:

service service-manager stop

**Comment by erazor1112** [comment]
There should be different commands depending on the Version of the Connector.

**Comment by netapp-bcammett** [comment]
Hi @erazor1112, thank you for submitting this feedback.

Which version of the Connector are you running?

Thanks,
Ben

**Comment by erazor1112** [comment]
3.9.27/2

**Comment by erazor1112** [comment]
there is one more command that is not working...
"--security packages not found..."

yum -y update –-security

**Comment by netapp-bcammett** [comment]
@erazor1112,

Are you using CentOS or RHEL?

I see "yum update --security" listed in this Red Hat doc:
https://access.redhat.com/sites/default/files/attachments/rh_yum_cheatsheet_1214_jcs_print-1.pdf

Thanks,
Ben

**Comment by erazor1112** [comment]
I'm from NetApp and my customer is using centos. So i think we need to but both options in there...
