### ISSUE TITLE
Could you please add the info about how to stop&start the connector in this page?

### ISSUE THREAD

**Issue by Xinwei-Wang** [NetAppDocs/cloud-manager-setup-admin#174]
Page: [Managing existing Connectors](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-managing-connectors.html)

Could you please add the info about how to stop&start the connector in this page?
Because there is no such info but it's necessary for customer to know.

**Comment by Xinwei-Wang** [comment]
Hi Ben, sorry for late response.
I got a case from the customer who request the method of how to stop the connector temporarily as their own requirement(no matter for what reason, they just need or want to do that.)
we have CVO stop feature on BlueXP , but we don't have the connector stop feature, so it's need to stop the linux host on provider side, just make this point on the document is fine that customer won't have such queries any more.

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-managing-state.html#scheduling-automatic-shutdowns-of-cloud-volumes-ontap

Thanks
Edwin

**Comment by netapp-bcammett** [comment]
@Xinwei-Wang,

Operating system and VM maintenance for the Connector is described on the top of this page:
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-managing-connectors.html

Thanks again for your feedback.

Regards,
Ben
