### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by wjthompson-ntap** [NetAppDocs/cloud-manager-setup-admin#177]
Page: [Security group rules in Azure](https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-ports-azure.html)

The hyperlink for [Learn more about the Connector’s proxy server](https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-ports-azure.html#Proxy%20server%20for%20AutoSupport%20messages). appears to be broken and perhaps referring to itself versus a different docs link.

**Comment by netapp-bcammett** [comment]
@wjthompson-ntap,

I fixed the link. Thank you for pointing this out.

Thanks again,
Ben
