### ISSUE TITLE
grammatical inconsistency

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/cloud-manager-setup-admin#183]
Page: [Set up and administer BlueXP](https://docs.netapp.com/us-en/cloud-manager-setup-admin/index.html)

The title string is used inconsistently:

![image](https://user-images.githubusercontent.com/56453501/230442181-42e91c37-01db-4f45-9fee-7aea7510aa51.png)

By strict guidelines, "set up" is the verb and "setup" is the noun. Even by looser standards that allow "setup" as the verb, the inconsistency in construction on the same page is distracting.

On the landing page title, it's verb+verb: _Set up and administer_. In the breadcrumb and sidebar, it's verb+noun: _Set up and administration_.

**Comment by netapp-bcammett** [comment]
Exactly why it's great to get peer reviews. You stop seeing certain things after awhile. I fixed the issue.

Thank you!
