### ISSUE TITLE
Subscribe to BlueXP in Azure Marketplace workflow documentation looks outdated

### ISSUE THREAD

**Issue by dismn8r** [NetAppDocs/cloud-manager-setup-admin#205]
Page: [Subscribe to BlueXP (standard mode)](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-subscribe-standard-mode.html)
Assuming this is the first time customer has logged into BlueXP...
No mention is made of a step for adding the appropriate Azure credentials first that will present the Associate Subscription action menu item, as described in the workflow.  Not all Azure credentials present the Associate Subscription option.

**Comment by netapp-bcammett** [comment]
@dismn8r, thank you for providing this feedback.

The assumption is that a user followed the previous "get started" pages to create a Connector, in which case credentials would be available. However, that's a poor assumption. I'll update the page to mention the requirement that you must add credentials first before you can subscribe and provide links to the appropriate pages.

Thanks again for reaching out.

Regards,
Ben

**Comment by netapp-bcammett** [comment]
I made a few updates:

- Clarified the services that the marketplace subscriptions enable charging for.
- Added that you need to associate a subscription with the credentials for a Connector.
- Clarified in step 2 that the credentials must be associated with a Connector. Credentials that are associated with BlueXP won't work.
- Added a related links section at the end

Thanks again for submitting your feedback. Please let me know if you have any additional feedback.

Regards,
Ben
