### ISSUE TITLE
Shared VPC Permissions missing Setup as a Service Account

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/cloud-manager-setup-admin#25]
Page: [Create a Connector in Google Cloud from Cloud Manager](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-gcp.html)

The table on this page listing the permissions required for Shared VPC Permissions is missing an entry for the "Setup As a Service User Account"   (This is the user account mentioned in Step 1 of setting up permissions: `"Ensure that the GCP user who deploys the Connector has the permissions in the [Connector deployment policy for GCP](https://occm-sample-policies.s3.amazonaws.com/Setup_As_Service_3.7.3_GCP.yaml)."`

This user requires the "compute.networkUser" permission in the host project.  Without this permission the user will not be able to deploy a connector as it will not be able to see the VPCs in the host project.

**Comment by mimitche** [comment]
Hi Ben-  That's exactly it.

Thanks,
Mike

**Comment by netapp-bcammett** [comment]
@mimitche and @felix-melligan 

How does the addition in the first row look?

![image](https://user-images.githubusercontent.com/18287750/167006637-b3d28925-3be4-4830-bab2-9ced98a7e4f6.png)

Two quesitons:

1. Is "Organization" the right term for the third column?
2. In column four, is it correct to say that the [Set up as Service](https://occm-sample-policies.s3.amazonaws.com/Setup_As_Service_3.7.3_GCP.yaml) permissions are "Service project permissions"?

**Comment by felix-melligan** [comment]
Hey Ben,

I think that solves the situation!

Will should we link to it in the section of the docs that talks about deploying the connector?

Thanks,

Felix

On May 5, 2022, at 15:10, Ben Cammett ***@***.***> wrote:

﻿

@mimitche<https://github.com/mimitche> and @felix-melligan<https://github.com/felix-melligan>

How does the addition in the first row look?

[image]<https://user-images.githubusercontent.com/18287750/167006637-b3d28925-3be4-4830-bab2-9ced98a7e4f6.png>

Two quesitons:

  1.  Is "Organization" the right term for the third column?
  2.  In column four, is it correct to say that the Set up as Service<https://occm-sample-policies.s3.amazonaws.com/Setup_As_Service_3.7.3_GCP.yaml> permissions are "Service project permissions"?

**Comment by mimitche** [comment]
Looks good- as to your questions:

1) I believe Service Project is the right term for this and not Organization
2) Correct, Service Project Permissions

**Comment by netapp-bcammett** [comment]
@mimitche,

So that means Google user accounts can be assigned to a specific service project? I tried looking in Google's docs but couldn't figure this out.

**Comment by mimitche** [comment]
Ben-

Correct.  In the example lab environment pasted below the test account "mike@mmconsult" is assigned to this particular service project with the Setup As A Service permissions. (The role is named "NetApp Cloud Central" in this example)

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/33675510/167417812-7bebfc85-ed6e-47fe-92c8-cf96f01b6e16.png">

When I switch the the host project you can see that the same user has been added as "Compute Network User" for the host project:
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/33675510/167418253-7450b57c-22ba-4250-96a6-6c643102138c.png">
