### ISSUE TITLE
Wll Freemium / BYOL CVO  shutting down after losing communication with Connector for longer than 14 days?

### ISSUE THREAD

**Issue by imasafum** [NetAppDocs/cloud-manager-setup-admin#27]
Page: [Learn about Connectors](https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html)

Regarding below sentence,
"If a Connector is powered down, Cloud Volumes ONTAP PAYGO systems will shut down after losing communication with a Connector for longer than 14 days."
Does this behavior that CVO will shutting down is effected including Freemium and BYOL?
In my understanding is yes, and If so, Cloud you please consider to add note to intent that including Freemium and BYOL?

Best regards,

Masafumi,

**Comment by netapp-bcammett** [comment]
Hi Masafumi,

Great question. I've sent a note off to the product team for confirmation.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
Hi Masafumi,

I updated the statement to note that this behavior applies to node-based licensing only.

Thanks again for reaching out with this question.

Regards,
Ben
