### ISSUE TITLE
Service based connector auto upgrade

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/cloud-manager-setup-admin#37]
Page: [Managing existing Connectors](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-managing-connectors.html)

The old docs used to show how to disable or turn on automatic connector upgrades (for the service based connector), but that seems to be missing from the doc. can we add it back please?

Below is a sample URL where this was shown.

https://docs.netapp.com/us-en/occm36/task_updating_cloud_manager.html#enabling-automatic-updates

**Comment by netapp-bcammett** [comment]
Hi @sabarig84,

That option was removed from the Cloud Manager user interface back in August 2020. All Connectors are enabled for automatic upgrades by default. If it needs to be changed, then I would reach out to the Cloud Manager team via in-product chat for instructions.

Regards,
Ben
