### ISSUE TITLE
Correct AWS Connector default settings

### ISSUE THREAD

**Issue by jsuarezs** [NetAppDocs/cloud-manager-setup-admin#56]
Page: [Default configuration for the Connector](https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-connector-default-config.html)

Hello, the URL is specifying: The default system disk is a 50 GiB gp2 disk. However the Connector in AWS is deployed using a 100 GiB GPS disk instead of 50GiB as docs. Could you take a look at this please?

Thank you.

**Comment by netapp-bcammett** [comment]
Hi Javier,

I deployed a Connector and I see the same 100 GiB disk size that you see. I'll update the docs today to change the disk size in AWS.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
Fixed!

Thanks again!
