### ISSUE TITLE
Login with exisiting NSS accounts

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/cloud-manager-setup-admin#58]
Page: [Add and manage NetApp Support Site accounts in Cloud Manager](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-adding-nss-accounts.html)

Considering the move of migrating AIQ completely into CM, can we add how users with exisiting login's can login first time and use AIQ?

I see we have covered few things in the below links.
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-cvo-aiq-digital-advisor.html
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-cvo-aiq-digital-advisor.html#how-active-iq-digital-advisor-works-with-cloud-manager

But i guess we should also add how customers with existing NSS logins (that was announced as a part of June28,2022 release) can signup into cloudmanager and start using AIQ.

**Comment by netapp-bcammett** [comment]
I've already been in discussions with Sabari through email.

**Comment by netapp-bcammett** [comment]
As discussed, I updated the note on the sign up page to expand on the details about how the Log in with NetApp option doesn't add credentials to Cloud Manager in the Support Dashboard. That must be done separately to enable key Cloud Volumes ONTAP workflows and to enable Active IQ.

https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-signing-up.html

Thanks again for your help!
