### ISSUE TITLE
GCP connector default instance change

### ISSUE THREAD

**Issue by melatsg** [NetAppDocs/cloud-manager-setup-admin#62]
Page: [Default configuration for the Connector](https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-connector-default-config.html)

Hello,
I believe that the default VM is not a n1-standard-4 anymore but a n2-standard-4.

Would it be possible to change the doc ?

Thanks

**Comment by netapp-bcammett** [comment]
I deployed a Connector and it looks like you're right. I have reached out to the development team for confirmation, just to make sure it's not based on specific regions. I'll provide an update when I have the final answer.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
The doc update was made last week. Thanks again for letting me know!
