### ISSUE TITLE
Clarify shut down conditions

### ISSUE THREAD

**Issue by elliottn** [NetAppDocs/cloud-manager-setup-admin#63]
Page: [Learn about Cloud Manager](https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-overview.html)

The current doc says
`Cloud Volumes ONTAP PAYGO systems with node-based licensing will shut down after losing communication with a Connector for longer than 14 days`

Please expand on if capacity based licensing or BYOL will experience the same behavior confirming if it will or will not be subject to the 14 day timer.  Seems like it will not but my team of CSA's did question if that was true.

**Comment by netapp-bcammett** [comment]
@elliottn,

Thank you for reaching out. I've sent a message off to the product manager to get an update on the status of this scenario when capacity-based licensing is used.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
Discussed internally. Closing the issue.
