### ISSUE TITLE
Language needs to be selected again after going to the next page

### ISSUE THREAD

**Issue by yukakou** [NetAppDocs/cloud-manager-setup-admin#64]
Page: [Set up and administer Cloud Manager](https://docs.netapp.com/us-en/cloud-manager-setup-admin/index.html)

Hi, I'm creating this ticket to follow up on the feedback from the local team in Japan.
The English content is shown after selecting a section (highlighted in the screenshot below) from the top page of Cloud Manager (for example) in Japanese.
Can you please check if it is something your team can control, or something caused by a browser setting?

![image](https://user-images.githubusercontent.com/50446078/187820230-17c63bcf-3fec-4f1c-9e04-675a96b02fb3.png)

**Comment by ntap-bmegan** [comment]
@yukakou - I've created a development issue for this work. Since it's not really a feature of this repo, I'm closing this issue.
