### ISSUE TITLE
Connectors should remaing running example

### ISSUE THREAD

**Issue by neilmaldy** [NetAppDocs/cloud-manager-setup-admin#66]
Page: [Learn about Connectors](https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html)

https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html#connectors-should-remain-running

The current example mentions paygo:

For example, a Connector is a key component in the health and operation of Cloud Volumes ONTAP. If a Connector is powered down, Cloud Volumes ONTAP PAYGO systems with node-based licensing will shut down after losing communication with a Connector for longer than 14 days.

Could we please adjust this to include capacity licensing in the example?

**Comment by netapp-bcammett** [comment]
Discussing with Neil internally.

**Comment by netapp-bcammett** [comment]
After receiving confirmation from the product team, the phrase was updated to remove the phrase "with node-based licensing" since it applies to all licensing methods.

> If a Connector is powered down, Cloud Volumes ONTAP PAYGO systems will shut down after losing communication with a Connector for longer than 14 days.

Thanks again for providing this feedback.
