### ISSUE TITLE
https://cloudmanager.cloud.netapp.com endpoint missing from Connector Endpoint requirements

### ISSUE THREAD

**Issue by trevorjth** [NetAppDocs/cloud-manager-setup-admin#77]
Page: [Getting started checklist](https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html)

![image](https://user-images.githubusercontent.com/109701535/192611274-b93be222-6d5e-4e8d-92bd-f63f790abc51.png)

In the table for "Outbound Networking for Connector".  We need to add another endpoint that the connector reaches out to:
https://cloudmanager.cloud.netapp.com

The endpoint https://*.cloudmanager.cloud.netapp.com does not capture the above URL that the connector tries to reach out to:
Request timeout to cloudmanager.cloud.netapp.com/20.44.75.43:443 after 30000 ms

**Comment by netapp-bcammett** [comment]
@trevorjth,

Thank you for submitting this feedback. I've reached out to the product team for clarification to confirm that we do in fact need to list both of these:

https://cloudmanager.cloud.netapp.com
https://*.cloudmanager.cloud.netapp.com

Or if https://cloudmanager.cloud.netapp.com is sufficient on its own. We know that URL is required based on your findings.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
https://cloudmanager.cloud.netapp.com was added to the list of endpoints.

Thanks,
Ben
