### ISSUE TITLE
In the case of federated environment - Please document the interface for the Cloud Manager SaaS and Cloud Manager Connector

### ISSUE THREAD

**Issue by venukntap** [NetAppDocs/cloud-manager-setup-admin#79]
Page: [Learn about Connectors](https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html)
In the of federated environment - Does the customer should use cloudmanager.netapp.com or the private IP address of a Connector?. Please document the interface difference of the SaaS portal and the interface on the connector for the federated environment.

**Comment by netapp-bcammett** [comment]
Hi Venu,

I'm working on updates to the documentation to better differentiate the use of Cloud Manager in Government regions from Commercial (SaaS) regions. I'll include these details in the update.

Thanks,
Ben

**Comment by venukntap** [comment]
Hi Ben - 
As discussed the request is related to Active Directory Federation. Thanks for checking!

Regards,
Venu

**Comment by netapp-bcammett** [comment]
After discussing with @venukntap, this issue can be closed.
