### ISSUE TITLE
New requirements for NSS account

### ISSUE THREAD

**Issue by laagabi** [NetAppDocs/cloud-manager-setup-admin#80]
Page: [Add and manage NetApp Support Site accounts in Cloud Manager](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-adding-nss-accounts.html)

Can we please update the docs to reflect the recent changes that got introduced with the new feature in Cloud Manager for support case creation:

- We only allow one NSS account per NetApp account

**Comment by netapp-bcammett** [comment]
Thank you for submitting this issue. I wasn't aware, so I'll confirm with the product team first to better understand how this works.

**Comment by netapp-bcammett** [comment]
I heard that this issue was fixed in the product, so I'm going to close this.
