### ISSUE TITLE
PAYGO system warning but what about other licensing approaches?

### ISSUE THREAD

**Issue by alexmal98** [NetAppDocs/cloud-manager-setup-admin#89]
Page: [Learn about Connectors](https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html)

There is a warning about PAYGO CVOs shutting down after 14 days without communication from the Connector.  But does the same 14 day rule apply for other licensing approaches? Such as customers using BYOL?

**Comment by netapp-bcammett** [comment]
@alexmal98,

This only applies to PAYGO.

**Comment by alexmal98** [comment]
Hi Ben,

Thanks, I am wondering what will happen if the Connector is powered down if
the customer has a BYOL licensing approach?

Thanks,
Alex

**Comment by netapp-bcammett** [comment]
Alex,

Does the following update clear up any confusion:

> A Connector should remain running at all times. It's important for the continued health and operation of the services that you enable.
> 
> For example, a Connector is a key component in the health and operation of Cloud Volumes ONTAP. If a Connector is powered down, Cloud Volumes ONTAP PAYGO systems and capacity-based BYOL systems will shut down after losing communication with a Connector for longer than 14 days.
> 
> NOTE: If your Cloud Volumes ONTAP system has a node-based BYOL license, the system will remain running after 14 days because the license is installed on the Cloud Volumes ONTAP system.

Thanks,
Ben
