### ISSUE TITLE
Regarding the Connector VM Outbound internet access - customer requests how the Connector authenticates to the endpoints

### ISSUE THREAD

**Issue by venukntap** [NetAppDocs/cloud-manager-setup-admin#90]
Page: [Create a Connector in Google Cloud from Cloud Manager](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-gcp.html)

Customer requests additional column - authentication account used by the Connector VM to the below endpoints.

https://support.netapp.com/
https://*.cloudmanager.cloud.netapp.com/
https://cloudmanagerinfraprod.azurecr.io/
https://*.blob.core.windows.net/
https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
https://s3.amazonaws.com/aws-cli/awscli-bundle.zip
https://*.blob.core.windows.net/ or https://hub.docker.com/

**Comment by netapp-bcammett** [comment]
Thank you for submitting this feedback. I reached out to the product team for confirmation. I'm waiting for a response.

**Comment by netapp-bcammett** [comment]
@venukntap was able to get the information that he needed, but no doc update is needed at this time.
