### ISSUE TITLE
Type "iam:GetInstanceProfiles"

### ISSUE THREAD

**Issue by promiseowolabi** [NetAppDocs/cloud-manager-setup-admin#96]
Page: [AWS permissions for the Connector](https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-permissions-aws.html)

This should be "iam:GetInstanceProfile"

**Comment by netapp-bcammett** [comment]
@promiseowolabi,

Thank you for submitting this issue. I updated the docs to fix the name of the permission in the policy.

Please don't hesitate to reach out if you have any additional feedback.

Thanks,
Ben
